version: '3.9'

services:
  zincsearch:
    image: ./zinc-server
    environment:
      - ZINC_FIRST_ADMIN_USER=${ZINC_FIRST_ADMIN_USER}
      - ZINC_FIRST_ADMIN_PASSWORD=${ZINC_FIRST_ADMIN_PASSWORD}
    ports:
      - "4080:4080"
    container_name: zincsearch
  api:
    build: 
      context: ./search-api
      args:
        ZINC_FIRST_ADMIN_USER: $ZINC_FIRST_ADMIN_USER
        ZINC_FIRST_ADMIN_PASSWORD: $ZINC_FIRST_ADMIN_PASSWORD
    environment:
      - ZINC_SERVER_URL: http://zinc-server:4080/api
    ports:
      - "8080:8080"
    depends_on:
      - zincsearch
  
  web:
    build: 
      context: ./search-client
      args:
        VITE_API_URL: $VITE_API_URL
    ports:
      - "80:8080"
    depends_on:
      - api